#!/bin/bash
# Run job through bash shell
#$ -S /bin/bash
#
# Your job name
#$ -N coverage
#
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Send an email after the job has finished
#$ -m e
#$ -M echavezaparicio@gmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh


name="SRR822853"

#Dirección padre de los archivos a usar (aquí debe estar el indice de segemehl)
HOME="/mnt/Timina/mhernandez/echavez"
#Habilitación de scripts personales
PATH=$PATH:$HOME/bin


module load htslib/1.2.1
module load samtools

#	Detección de flancos
awk -v OFS='\t' '{print $1,$2-20,$2}' ${name}_splitreads_Bloq.bed > ${name}_splitreads_BloqLeft.bed
awk -v OFS='\t' '{print $1,$3,$3+20}' ${name}_splitreads_Bloq.bed > ${name}_splitreads_BloqRight.bed

#	Cuenta de profundidad
samtools bedcov -j ${name}_splitreads_Bloq.bed ${name}_1_cured_AlS_sorted.bam > coverarge_del.bed
samtools bedcov -j ${name}_splitreads_BloqLeft.bed ${name}_1_cured_AlS_sorted.bam > coverarge_left.bed
samtools bedcov -j ${name}_splitreads_BloqRight.bed ${name}_1_cured_AlS_sorted.bam > coverarge_right.bed

#	Computo de razón de profundidad y filtro de alelos
Allelic_Filter coverarge_del.bed coverarge_left.bed coverarge_right.bed 0.025 > ${name}_NotAllel.bed
