#!/bin/bash
# Run job through bash shell
#$ -S /bin/bash
#
# Your job name
#$ -N BED_histogram
#
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Send an email after the job has finished
#$ -m e
#$ -M echavezaparicio@gmail.com
#

##---------------------------------------------------------
#	DESCRIPCIÓN
#   
#   
#	Importante:
#   
#	IN:
#
#	OUT:
#									También hace el análisis del perfil de deleciones
#
##---------------------------------------------------------

##---------------------------------------------------------
#	USO
#	
#
##---------------------------------------------------------

##---------------------------------------------------------
#	TO DO LIST
#	
##---------------------------------------------------------


########	ZONA DE CONFIGURACIÓN

####	Variables de entrada

#	Nombre de los archivos bam y bed sin extensión
BAM="SRR822857_sort"
BED="SRR822857_splitreads_bedcov"


#Dirección padre de los archivos a usar (aquí debe estar el indice de segemehl)
HOME="/mnt/Timina/mhernandez/echavez"
#Habilitación de scripts personales
PATH=$PATH:$HOME/bin

########	ZONA DE SCRIPT

# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh

module load htslib/1.2.1
module load samtools

samtools view -Lbh ${BED}.bed ${BAM}.bam > ${BED}_view.bam
samtools index ${BED}_view.bam
