#!/bin/bash
# Run job through bash shell
#$ -S /bin/bash
#
# Your job name
#$ -N SRA_pipe_download
#
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Send an email after the job has finished
#$ -m e
#$ -M echavezaparicio@gmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh

##---------------------------------------------------------
#   DESCRIPCIÓN
#   
#   Este programa crea lo necesario para descargar los fastq y alinearlos
#   Obtieene el sra y los progrmanas para descargar los split files
#   las partes están calculadas en segmentos de 900 000 000 reads
#   Crea programas intermedios que revisan la integridad de los archivos
#   
#   Importante:
#   Se tiene que ejecutar dentro de la carpeta ${name}_file
#   Si no eres Edgar Iván Chávez Aparicio, Edita:
#           la parte de arriba ^ (lineas 2-16)
#           la parte de abajo  v (linea 70)
#   
#   IN:
#       name                = nombre de acceso del SRA
#       n_spots             = numero de spots leidos (segun SRA)
#       n_threads           = numero de hilos para usar en el alineamiento
#       quality_treshold    = Phred mínimo para la edición de fastas
#       HOME                = Carpeta de Trabajo (dondo se encuentra el Indx de segemehl y la subcarpeta ${name}_file)
#       HumanRef            = Dirección del archivo de genoma de referencia para el alineamiento
#   
#   OUT (por cada subcarpeta):
#       DumpANDtest$i.sge   = sge listo para obtener los comprimidos
#       Edit$i.sge          = sge para editar por medio de fastx
#       Alignment$i.sge     = sge listo para ejecutar de alineamiento
#       
##---------------------------------------------------------

##---------------------------------------------------------
#   TO DO LIST
#   
#   Variable de n_part_spots
#   Divición de reads pareja
#
#   Guía de uso
##---------------------------------------------------------


########    Config Zone

name="ERR318658"
n_spots="1608506593"
n_threads="32"
quality_treshold="28"

#Dirección padre de los archovos a usar (aquí debe estar el indice de segemehl)
HOME="/mnt/Timina/mhernandez/echavez"
#Dirección del genoa de referencia a usar
HumanRef="/mnt/Archives/genome/human/hg38/UCSC/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa"
#Tu correo para ser avisado
email="echavezaparicio@gmail.com"

########    Script zone

#   Calculo de hilos de descarga

n_th=$(($n_spots / 900000000 +1))

echo $n_th threads to use

for i in `seq 1 $n_th`
    do
                indx_i[$i]=$((($i-1)*900000000 +1))
                indx_f[$i]=$((($i)*900000000))
    done 
indx_f[$n_th]=$n_spots

#   Descarga del SRA

wget ftp://ftp-trace.ncbi.nih.gov/sra/sra-instant/reads/ByRun/sra/${name:0:3}/${name:0:6}/$name/$name.sra

echo $name downloaded

#   fastq-dump

for i in `seq 1 $n_th`
    do
    
    #crear folder
    
    mkdir $HOME/${name}_file/${name}_${i}
    
        printf "#!/bin/bash
# Run job through bash shell
#\n#$ -S /bin/bash
#
# Your job name
#\n#$ -N DumpANDtest$i
#
# Use current working directory
#\n#$ -cwd
#
# Join stdout and stderr
#\n#$ -j y
#
# Send an email after the job has finished
#\n#$ -m e
#\n#$ -M $email
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load sra
module load fastqc
#


export HOME=$HOME

# Obtener los archovivos del .sra

fastq-dump -split-files -N ${indx_i[$i]} -X ${indx_f[$i]} -gzip -O $HOME/${name}_file/${name}_${i} $HOME/${name}_file/$name.sra


# Control de errores

echo gzip tail de ${name}${i}_1
zcat ${name}_1.fastq.gz | tail -n40 > ${name}${i}/tail_1.txt

echo gzip tail de ${name}${i}_2
zcat ${name}_2.fastq.gz | tail -n40 > ${name}${i}/tail_2.txt

# Revisa los comprimidos, si estan bien, -> fastqc

gz_test=\$( gunzip -t ${name}_1.fastq.gz)

echo \"gz_test 1 \"
echo \$gz_test
if [[ -z \"\$gz_test\" ]]
\t then

\t echo qc 1
\t fastqc ${name}_1.fastq.gz

fi \n

gz_test=\$( gunzip -t ${name}_2.fastq.gz)

echo \"gz_test 2 \"
echo \$gz_test
if [[ -z \"\$gz_test\" ]]
\t then

\t echo qc 2
\t fastqc ${name}_2.fastq.gz

fi \n

" > $HOME/${name}_file/${name}_${i}/DumpANDtest$i.sge


echo DumpANDtest$i creado


#   Creación del programa de Edición
printf "#!/bin/bash
# Run job through bash shell
#\n#$ -S /bin/bash
#
# Your job name
#\n#$ -N Edit$i
#
# Use current working directory
#\n#$ -cwd
#
# Join stdout and stderr
#\n#$ -j y
#
# Send an email after the job has finished
#\n#$ -m e
#\n#$ -M $email
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
########    Config Zone

file_names=(\"${name}_1.fastq.gz\" \"${name}_2.fastq.gz\")

########    Script zone

module load fastx

#   Calculo de hilos de descarga

echo Pipe Init

for i in \`seq 1 \${#file_names[@]}\`
    do
    
    echo \${file_names[\$i-1]}
    name=\$(echo \${file_names[\$i-1]} | cut -f1 -d\".\" )
    gunzip -c \${file_names[\$i-1]} | fastq_quality_trimmer -t $quality_treshold -z -v -o \${name}_cured.fastq.gz
    fastqc ${name}_cured.fastq.gz
    done
\n" > $HOME/${name}_file/${name}_${i}/Edit$i.sge

echo Edit$i.sge creado

#Creación del programa de alineamiento
printf "#!/bin/bash
# Run job through bash shell
#\n#$ -S /bin/bash
#
# Your job name
#\n#$ -N Align_S_$i
#
# Use current working directory
#\n#$ -cwd
#
# Join stdout and stderr
#\n#$ -j y
#
# Send an email after the job has finished
#\n#$ -m e
#\n#$ -M $email
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load segemehl
module load samtools

#
# pe (Parallel environment)request a parallel environment (MPI, OpenMP). Set your number of requested slots here.
#\n#$ -pe openmpi $n_threads

#construcción de segemehl pareado con -S

echo Align 1
segemehl.x -i $HOME/Idx_Human.idx -S -d $HumanRef -q ${name}_1_cured.fastq.gz -t $n_threads | samtools view -Sbh > ${name}_1_cured_AlS.bam

echo Align 2
segemehl.x -i $HOME/Idx_Human.idx -S -d $HumanRef -q ${name}_2_cured.fastq.gz -t $n_threads | samtools view -Sbh > ${name}_2_cured_AlS.bam
" > $HOME/${name}_file/${name}_${i}/Alignment_$i.sge

echo Alignment_$i.sge creado

    done