#!/bin/bash
# Run job through bash shell
#$ -S /bin/bash
#
# Your job name
#$ -N Circular
#
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Send an email after the job has finished
#$ -m e
#$ -M echavezaparicio@gmail.com
#

##---------------------------------------------------------
#	DESCRIPCIÓN
#   
#	Este programa crea
#   
#	Importante:
#   
#	IN:
#		file_names		= Nombres de raiz en los sam y bed
#
#	OUT:
#		${file_names[$i]}_splitreads.sam		= Archivo con split reads
#		${file_names[i]}_C.fastq.sngl.sam		= Archivo de Circulares
#		${file_names[i]}_B.fastq.sngl.sam		= Archivo de Backsplits
#		${file_names[$i]}_splitreads_Chr${j}.sam		= split reads separados por cromosoma
#		stairways_${file_names[$i]}_Chr${j}.sge		= sge para analizar los plit reads
#
##---------------------------------------------------------

##---------------------------------------------------------
#	TO DO LIST
#	
#	Comentar
#	Guía de uso
##---------------------------------------------------------


########	Config Zone

####	Variables de entrada

file_names=("ERR318661_1_cured")
Chr=("chr1")
# "chr2" "chr3" "chr4" "chr5" "chr6" "chr7" "chr8" "chr9" "chr10" "chr11" "chr12" "chr13" "chr14" "chr15" "chr16" "chr17" "chr18" "chr19" "chr20" "chr21" "chr22" "chr23")

####	Direcciones

#Dirección padre de los archivos a usar (aquí debe estar el indice de segemehl)
HOME="/mnt/Timina/mhernandez/echavez"
#Habilitación de scripts personales
PATH=$PATH:$HOME/bin
#Tu correo para ser avisado
email="echavezaparicio@gmail.com"

########	Script zone


for i in `seq 0 (${#file_names[@]}-1)`
	do

	echo File ${file_names[$i]}
	
	egrep ";C;" ${file_names[$i]}.fastq.sngl.bed > ${file_names[$i]}_C.fastq.sngl.bed
	egrep ";B;" ${file_names[$i]}.fastq.sngl.bed > ${file_names[$i]}_B.fastq.sngl.bed

	echo parce
	cat ${file_names[$i]}.sam | SAM_parce_GAP.pl  > ${file_names[$i]}_splitreads.bed  #SAM
	echo search C
	search_bed_sam.pl ${file_names[i]}_C.fastq.sngl.bed ${file_names[i]}.sam > ${file_names[i]}_C.fastq.sngl.sam # bed sam C
	echo search B
	search_bed_sam.pl ${file_names[i]}_B.fastq.sngl.bed ${file_names[i]}.sam > ${file_names[i]}_B.fastq.sngl.sam # bed sam B
	
	for j in `seq 0 (${#Chr[@]}-1)`
		do
	
		# sam del cromosoma
		echo obtaining ${file_names[$i]}_splitreads_${Chr[$j]}.bed
		grep -P "^${Chr[$j]}\t" ${file_names[$i]}_splitreads.bed  > ${file_names[$i]}_splitreads_${Chr[$j]}.bed
		
		printf "#!/bin/bash
# Run job through bash shell
\n#$ -S /bin/bash
#
# Your job name
\n#$ -N stairways_${file_names[$i]}_${Chr[$j]}
#
# Use current working directory
\n#$ -cwd
#
# Join stdout and stderr
\n#$ -j y
#
# Send an email after the job has finished
\n#$ -m e
\n#$ -M $email
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh

##---------------------------------------------------------
#	DESCRIPCIÓN
#   
#	Este programa crea los archivos sam divididos por bloques.
#   
#	Importante:
#   
#	IN:
#		Variable		= Explicación
#
#	OUT:
#		Variable		= Explicación

##---------------------------------------------------------

##---------------------------------------------------------
#	TO DO LIST
#   
##---------------------------------------------------------


########	Config Zone

####	Variables de entrada


####	Direcciones

#Dirección padre de los archivos a usar (aquí debe estar el indice de segemehl)
HOME="/mnt/Timina/mhernandez/echavez"
#Habilitación de scripts personales
PATH=$PATH:$HOME/bin

########	Script zone


sort -k2 -n ${file_names[$i]}_splitreads_${Chr[$j]}.bed | stairways_BED.pl > ${file_names[$i]}_splitreads_${Chr[$j]}_stairs.bed

" > stairways_${file_names[$i]}_${Chr[$j]}.sge
		echo stairways_${file_names[$i]}_${Chr[$j]}.sge created
		done
	done
	